apiVersion: apps/v1
kind: Deployment
metadata:
  name: hipstershop
spec:
  selector:
    matchLabels:
      app: hipstershop
  template:
    metadata:
      labels:
        app: hipstershop
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: email
          image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.0
          ports:
            - containerPort: 6060
          env:
            - name: PORT
              value: "6060"
            # - name: DISABLE_TRACING
            #   value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:6060"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:6060"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: checkout
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.0
          ports:
            - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "localhost:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "localhost:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "localhost:50060"
            - name: EMAIL_SERVICE_ADDR
              value: "localhost:6060"
            - name: CURRENCY_SERVICE_ADDR
              value: "localhost:7000"
            - name: CART_SERVICE_ADDR
              value: "localhost:7070"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: recommendation
          image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.0
          ports:
            - containerPort: 9090
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
          env:
            - name: PORT
              value: "9090"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "localhost:3550"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: DISABLE_DEBUGGER
          #   value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi
        - name: payment
          image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.0
          ports:
            - containerPort: 50060
          env:
            - name: PORT
              value: "50060"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50060"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50060"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: productcatalog
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.0
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:3550"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:3550"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: cart
          image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.0
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "localhost:6379"
            - name: PORT
              value: "7070"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 15
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
        - name: currency
          image: gcr.io/google-samples/microservices-demo/currencyservice:v0.2.0
          ports:
            - name: grpc
              containerPort: 7000
          env:
            - name: PORT
              value: "7000"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: DISABLE_DEBUGGER
          #   value: "1"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: shipping
          image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.0
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        - name: ad
          image: gcr.io/google-samples/microservices-demo/adservice:v0.2.0
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          #- name: JAEGER_SERVICE_ADDR
          #  value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
        - name: frontend
          image: gcr.io/google-samples/microservices-demo/frontend:v0.2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "localhost:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "localhost:7000"
            - name: CART_SERVICE_ADDR
              value: "localhost:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "localhost:9090"
            - name: SHIPPING_SERVICE_ADDR
              value: "localhost:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "localhost:5050"
            - name: AD_SERVICE_ADDR
              value: "localhost:9555"
            - name: ENV_PLATFORM
              value: "gcp"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hipstershop
spec:
  type: ClusterIP
  selector:
    app: hipstershop
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hipstershop-external
spec:
  type: LoadBalancer
  selector:
    app: hipstershop
  ports:
    - name: http
      port: 80
      targetPort: 8080
